title = "Resume example"

# Contact
# name
# email
# phone
# linkedin
# github
[contact]
name = "Steve Jobsfinder"
email = "jobsfinder@crapple.com"
phoneNumber = "123-456-7890"
linkedin = "https://linkedin.com/in/jobsfinder"
github = "https://github.com/jobsfinder"

# Education
# List your schools/training
    # name
    # degree
    # graduation date 
[[education]]

[[education.1]]
name = "Northsouthern University"
degree = "B.S. Marketing"
graduation_date = "May 1970"

[[education.2]]
name = "Southnorthern University"
degree = "MBA"
graduation_date = "May 1972"

# Experience
# List your experience
    # Company
    # Role
    # Start Date
    # End Date
    # Relevant tasks
[[experience]]

[[experience.1]]
company = "Crapple Inc"
role = "Founder/CEO"
start_date = "Jan 1976"
end_date = "Sep 1985"
tasks = [
    "Founded an electronics startup in a garage ", 
    "Designed the overpriced electronics for the masses"
]

[[experience.2]]
company = "Flixar"
role = "Owner"
start_date = "May 1986"
end_date = "Sep 2006"
tasks = [
    "funded company that made janky 3d animated films using computer graphics after getting kicked out at Crapple", 
    
]
# Skills and Interests
# List your skills
    # skillGroup
    # subSkill
[[skills]]

[[skill.1]]
skillGroup = "Design"
subskill = ""

[[skill.2]]
skillGroup = "Management"
subskill = ""

# Projects
# List your projects
    # project name
    # description of project
[[projects]]

[[projects.1]]
name = ""
description = ""

[[projects.2]]
name = ""
description = ""