title = "Resume example"

# Contact
# name
# email
# phone
# linkedin
# github
[contact]
name = "Steve Jobsfinder"
email = "jobsfinder@crapple.com"
phoneNumber = "123-456-7890"
linkedin = "https://linkedin.com/in/jobsfinder"
github = "https://github.com/jobsfinder"

# Education
# List your schools/training
    # name
    # degree
    # graduation date 
[[education]]
name = "Northsouthern University"
degree = "B.S. Marketing"
graduation_date = "May 1970"

[[education]]
name = "Southnorthern University"
degree = "MBA"
graduation_date = "May 1972"

# Experience
# List your experience
    # Company
    # Role
    # Start Date
    # End Date
    # Relevant tasks


[[experience]]
company = "Crapple Inc"
role = "Founder/CEO"
start_date = "Jan 1976"
end_date = "Sep 1985"
tasks = [
    "Founded an electronics startup in a garage ", 
    "Designed the overpriced electronics for the masses"
]

[[experience]]
company = "Flixar"
role = "Owner"
start_date = "May 1986"
end_date = "Sep 2006"
tasks = [
    "funded company that made janky 3d animated films using computer graphics after getting kicked out at Crapple", 
    "made cool movies like Boy Story, Creatures Inc, and Finding Teemo"
]
# Skills and Interests
# List your skills
    # skillGroup
    # subSkill

[[skills]]
skillGroup = "Languages"
subskill = "English, German, French, Spanish, Chinese"

[[skills]]
skillGroup = "Design"
subskill = "UX, UI, UCry"

[[skills]]
skillGroup = "Management"
subskill = "yelling, micro-managing, budget-cutting"

# Projects
# List your projects
    # project name
    # description of project
[[projects]]
name = "Crapple cryMac Computer"
description = "Lead designer of the desktop computer that is so bad it will bring you to tears"

[[projects]]
name = "Crapple cryPod"
description = "Designed an overpriced music player that actually doesn't really work that well"