[[education]]
name = "Northsouthern University"
degree = "B.S. Marketing"
graduation_date = "May 1970"

[[education]]
name = "Northsouthern University"
degree = "B.S. Marketing"
graduation_date = "May 1970"